replicaCount: 2

image:
  repository: ghcr.io/kayaman/mickey-service
  pullPolicy: Always
  tag: "0.0.8"

nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: mickey-service.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Service specific configuration
config:
  logLevel: 'info'
  apiPrefix: '/api/v1'

# Connection strings for dependencies will be templated
dependencies:
  database:
    enabled: true
    # These values would be overridden by the umbrella chart
    host: '{{ .Release.Name }}-postgresql'
    port: 5432
    database: 'mickey'
    username: 'mickey'
    # Password would be injected as a secret
