name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/Chart.yaml'
      - 'helm/values.yaml'
      - 'helm/templates/**'
    tags:
      - 'chart-*'
      - 'v*' # Also trigger on version tags
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Add Helm repository dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Bump chart version
        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/chart-')
        run: |
          # Extract tag and determine whether it's a chart-specific tag
          TAG=${GITHUB_REF#refs/tags/}

          if [[ $TAG == chart-* ]]; then
            # Extract version from chart tag (e.g., chart-1.2.3 -> 1.2.3)
            VERSION=${TAG#chart-}
          elif [[ $TAG == v* ]]; then
            # For app version tags, increment the patch version of the chart
            VERSION=$(grep '^version:' helm/Chart.yaml | awk '{print $2}')
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)
            NEW_PATCH=$((PATCH + 1))
            VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
          fi

          # Update chart version
          sed -i "s/^version: .*$/version: ${VERSION}/" helm/Chart.yaml

          # Commit changes
          git add helm/Chart.yaml
          git commit -m "Bump chart version to ${VERSION}" || echo "No changes to commit"
          git push origin master

      # Set up Helm chart-releaser
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          config: .github/cr.yaml

      # Optional: You can add here a step to push chart to another registry
      # For example OCI registry instead of GitHub Pages
